package eu.keep.downloader.db;

import eu.keep.softwarearchive.pathway.RegistryType;

/**
 * Class representing the Registry table in the SWA database. 
 * Simple extension of the autogenerated class RegistryType. 
 * @author Bram Lohman
 *
 */
public class DBRegistry extends RegistryType {

    public DBRegistry() {
    	super();
    }
    
    public DBRegistry(RegistryType registryType) {
    	this.name = registryType.getName();
    	this.url = registryType.getUrl();
    	this.className = registryType.getClassName();
    	this.translationView = registryType.getTranslationView();
    	this.enabled = registryType.isEnabled();
    	this.description = registryType.getDescription();
    	this.comment = registryType.getComment();
    	this.registryId = registryType.getRegistryId();
    }
    
    /**
     * Get the registry's ID
     * Equivalent to method getRegistryId (with lowercase d) in superclass.
     * This method kept for legacy reasons.
     * @return the registry ID
     */
	public int getRegistryID() {
		return getRegistryId();
	}
	/**
	 * Set the registry ID
     * Equivalent to method setRegistryId (with lowercase d) in superclass.
     * This method kept for legacy reasons.
	 * @param registryID the ID
	 */
	public void setRegistryID(int registryID) {
		setRegistryId(registryID);
	}

    public String toString() {
    	return "[" + registryId  + "]" + ":" + name;
    }
}
